insert into company (name, description) values ('Hansen-Wehner', 'Drainage of Right Tibia with Drainage Device, Perc Approach');
insert into company (name, description) values ('Gottlieb LLC', 'Drainage of L Ankle Jt with Drain Dev, Perc Endo Approach');
insert into company (name, description) values ('Dietrich LLC', 'Removal of Spacer from Right Ankle Joint, Perc Endo Approach');
insert into company (name, description) values ('Hettinger-Monahan', 'Detachment at Right Lower Arm, Low, Open Approach');
insert into company (name, description) values ('Dicki, Torp and Keeling', 'Excision of Left Upper Leg Muscle, Open Approach');
insert into company (name, description) values ('Funk Group', 'Drainage of L Metacarpophal Jt, Open Approach, Diagn');
insert into company (name, description) values ('Kris-Kuvalis', 'Transfusion of Autol WBC into Periph Vein, Open Approach');
insert into company (name, description) values ('Pfeffer Inc', 'Destruction of Thoracic Nerve, Percutaneous Approach');
insert into company (name, description) values ('Rath LLC', 'Supplement Right Pelvic Bone with Autol Sub, Perc Approach');
insert into company (name, description) values ('Balistreri LLC', 'Revision of Autol Sub in L Hip Jt, Extern Approach');
insert into company (name, description) values ('Lowe-Metz', 'Repair Left Buttock, Percutaneous Endoscopic Approach');
insert into company (name, description) values ('Crona Inc', 'Extracorporeal Therapies, Physiological Systems, Hypothermia');
insert into company (name, description) values ('O''Keefe, Kuhn and Bosco', 'Revision of Nonaut Sub in Penis, Perc Approach');
insert into company (name, description) values ('Wilkinson-Corwin', 'Dilate of L Brach Vein with Intralum Dev, Perc Endo Approach');
insert into company (name, description) values ('Donnelly and Sons', 'Supplement Sacrococcygeal Jt with Synth Sub, Perc Approach');
insert into company (name, description) values ('Nader-Gulgowski', 'Extraction of Sacral Nerve, Open Approach');
insert into company (name, description) values ('Schoen, Legros and Berge', 'Revision of Synth Sub in Lum Vertebra, Perc Approach');
insert into company (name, description) values ('Schaden-Okuneva', 'Fusion of Left Hip Joint with Autol Sub, Open Approach');
insert into company (name, description) values ('Howell Inc', 'Excision of Bilateral Ovaries, Percutaneous Approach, Diagn');
insert into company (name, description) values ('MacGyver, Powlowski and Lindgren', 'Drainage of Sup Mesent Vein, Perc Endo Approach, Diagn');
insert into company (name, description) values ('Hackett, Casper and Emmerich', 'Removal of Int Fix from L Humeral Head, Open Approach');
insert into company (name, description) values ('Hammes and Sons', 'Revision of Nonaut Sub in L Patella, Perc Endo Approach');
insert into company (name, description) values ('Wintheiser and Sons', 'Excision of Uterus, Open Approach');
insert into company (name, description) values ('Rohan, Haley and Boehm', 'Excision of Left Lacrimal Bone, Perc Endo Approach, Diagn');
insert into company (name, description) values ('Gibson-Williamson', 'Bypass Gastric Vein to Low Vein w Autol Vn, Perc Endo');
insert into company (name, description) values ('Kuhic, Farrell and Schiller', 'Revision of Int Fix in R Finger Phalanx Jt, Extern Approach');
insert into company (name, description) values ('Breitenberg, Trantow and Shanahan', 'Destruction of Sciatic Nerve, Percutaneous Approach');
insert into company (name, description) values ('Flatley-Bergstrom', 'Excision of Bilateral Breast, Open Approach, Diagnostic');
insert into company (name, description) values ('Yost, Homenick and Franecki', 'Replace Chest Skin w Autol Sub, Full Thick, Extern');
insert into company (name, description) values ('Rolfson, Feeney and Balistreri', 'Removal of Int Fix from R Metacarpal, Perc Endo Approach');
insert into company (name, description) values ('Lubowitz, Lind and Pfannerstill', 'Excision of Left Radius, Percutaneous Endoscopic Approach');
insert into company (name, description) values ('Kling, Smitham and Sporer', 'Introduction of Radioact Subst into Eye, Perc Approach');
insert into company (name, description) values ('Mante-Ebert', 'Removal of Synth Sub from Sternum, Perc Endo Approach');
insert into company (name, description) values ('Hartmann Inc', 'Supplement Intracran Art with Nonaut Sub, Perc Approach');
insert into company (name, description) values ('Boyer, Fisher and Osinski', 'Destruction of Cerebral Meninges, Open Approach');
insert into company (name, description) values ('Haag Group', 'Excision of Right Adrenal Gland, Open Approach');
insert into company (name, description) values ('Wyman-Smitham', 'Excision of Right Ankle Region, Percutaneous Approach');
insert into company (name, description) values ('Orn Group', 'Excision of Left Orbit, Open Approach');
insert into company (name, description) values ('Schamberger and Sons', 'Fusion 2-4 L Jt w Synth Sub, Post Appr P Col, Perc Endo');
insert into company (name, description) values ('Rohan, Carter and Kunde', 'Supplement L Ext Jugular Vein w Synth Sub, Perc Endo');
insert into company (name, description) values ('Purdy, Homenick and Hickle', 'Insertion of Int Fix into L Frontal Bone, Perc Endo Approach');
insert into company (name, description) values ('Smith, Moen and Ullrich', 'Occlusion R Cephalic Vein w Intralum Dev, Perc');
insert into company (name, description) values ('Zboncak, Kris and Upton', 'Division of Left Palatine Bone, Open Approach');
insert into company (name, description) values ('Reichert Inc', 'Destruction of Left Upper Femur, Percutaneous Approach');
insert into company (name, description) values ('Ankunding Group', 'Destruction of Right Axillary Vein, Open Approach');
insert into company (name, description) values ('Nienow, Rice and Mueller', 'Bypass 1 Cor Art from Cor Art with Autol Art, Open Approach');
insert into company (name, description) values ('Beatty, Metz and Bednar', 'Stereotactic Particulate Radiosurgery of Peripheral Nerve');
insert into company (name, description) values ('Jerde, Schinner and Marks', 'Excision of Left Nipple, External Approach');
insert into company (name, description) values ('Will, Streich and Runolfsson', 'Bypass Spinal Canal to Fallopian w Nonaut Sub, Open');
insert into company (name, description) values ('Kunde, Botsford and Ryan', 'Replace of L Brach Art with Nonaut Sub, Perc Endo Approach');
insert into company (name, description) values ('Feil Inc', 'Revision of Spacer in Left Ankle Joint, Open Approach');
insert into company (name, description) values ('Heller-Rice', 'Beam Radiation of Tongue using Photons <1 MeV');
insert into company (name, description) values ('Howe-Crona', 'Insertion of Artificial Sphincter into Anus, Perc Approach');
insert into company (name, description) values ('Hand-Padberg', 'Introduce Analg/Hypnot/Sedat in Mouth/Phar, Perc');
insert into company (name, description) values ('Dibbert-Schoen', 'Replacement of Sup Vena Cava with Nonaut Sub, Open Approach');
insert into company (name, description) values ('Reinger, Morissette and Prohaska', 'Release Thalamus, Percutaneous Endoscopic Approach');
insert into company (name, description) values ('Kub-Kessler', 'Radiation Therapy, Respiratory System, Other Radiation');
insert into company (name, description) values ('Turcotte, Rutherford and Friesen', 'Restriction of Stomach with Intralum Dev, Open Approach');
insert into company (name, description) values ('Toy, Hilpert and Collins', 'Revision of Nonaut Sub in R Radius, Extern Approach');
insert into company (name, description) values ('Senger, Stehr and Ziemann', 'Replacement of R Frontal Bone with Nonaut Sub, Perc Approach');
insert into company (name, description) values ('Rohan-Koelpin', 'Repair Cervicothoracic Vertebral Joint, Perc Approach');
insert into company (name, description) values ('Altenwerth-Kihn', 'Revise of Nonaut Sub in Prostate/Seminal Ves, Open Approach');
insert into company (name, description) values ('Schmitt Group', 'Repair Inferior Mesenteric Artery, Percutaneous Approach');
insert into company (name, description) values ('Schinner-Howe', 'Reposition Right Mandible, External Approach');
insert into company (name, description) values ('Buckridge-Hoeger', 'Removal of Infusion Device from Bladder, Endo');
insert into company (name, description) values ('Jacobson, Kirlin and Casper', 'Revision of Autol Sub in Brain, Extern Approach');
insert into company (name, description) values ('Ankunding and Sons', 'Replacement of Left Lens with Nonaut Sub, Perc Approach');
insert into company (name, description) values ('Kilback, Abbott and Sawayn', 'Excision of Left Subclavian Artery, Perc Endo Approach');
insert into company (name, description) values ('Waelchi Inc', 'Division of Left Hip Bursa and Ligament, Perc Endo Approach');
insert into company (name, description) values ('Toy Inc', 'Excision of Left Upper Lobe Bronchus, Open Approach');
insert into company (name, description) values ('Rath and Sons', 'Measurement of Cardiac Rhythm, Percutaneous Approach');
insert into company (name, description) values ('Rippin LLC', 'Destruction of Thoracic Nerve, Percutaneous Approach');
insert into company (name, description) values ('D''Amore, Frami and Auer', 'Fusion of R Temporomandib Jt with Synth Sub, Open Approach');
insert into company (name, description) values ('Lang-Terry', 'Insertion of Int Fix into L Parietal Bone, Open Approach');
insert into company (name, description) values ('Roberts-Oberbrunner', 'Supplement Portal Vein with Nonaut Sub, Open Approach');
insert into company (name, description) values ('Dooley, Powlowski and Blanda', 'Dilation of Stomach, Pylorus, Perc Endo Approach');
insert into company (name, description) values ('Blick Inc', 'Beam Radiation of Thyroid using Photons >10 MeV');
insert into company (name, description) values ('Cummings-Dickens', 'Repair Trachea, Via Natural or Artificial Opening');
insert into company (name, description) values ('Gusikowski LLC', 'Insertion of Infusion Dev into L Subclav Art, Perc Approach');
insert into company (name, description) values ('Anderson, Bernhard and DuBuque', 'Repair Left Kidney Pelvis, Endo');
insert into company (name, description) values ('Gislason and Sons', 'HDR Brachytherapy of Trachea using Iodine 125');
insert into company (name, description) values ('West-Nicolas', 'Excision of Left Vertebral Vein, Perc Endo Approach');
insert into company (name, description) values ('Paucek-Bergstrom', 'Revision of Nonaut Sub in Peritoneum, Perc Endo Approach');
insert into company (name, description) values ('Schaefer, Bins and Keeling', 'Release Right Temporal Bone, Open Approach');
insert into company (name, description) values ('Thompson-Yundt', 'Insertion of Radioactive Element into L Ankle, Open Approach');
insert into company (name, description) values ('McClure LLC', 'Excision of Right Tarsal Joint, Percutaneous Approach, Diagn');
insert into company (name, description) values ('Crooks-Pacocha', 'Revision of Drainage Device in Left Lung, Open Approach');
insert into company (name, description) values ('Keebler-Schimmel', 'Release Penis, External Approach');
insert into company (name, description) values ('Bogisich Inc', 'Restrict R Basilic Vein w Extralum Dev, Perc Endo');
insert into company (name, description) values ('Corkery Group', 'Fusion Thor Jt w Synth Sub, Ant Appr A Col, Perc');
insert into company (name, description) values ('Kilback, Ferry and Mitchell', 'Resection of Right Tarsal Joint, Open Approach');
insert into company (name, description) values ('Kling, Spencer and Kuphal', 'Division of Buttock Subcu/Fascia, Open Approach');
insert into company (name, description) values ('Padberg-Morar', 'Excision of Left Orbit, Open Approach, Diagnostic');
insert into company (name, description) values ('Shields, Schumm and Little', 'Excision of Right Sphenoid Bone, Perc Approach, Diagn');
insert into company (name, description) values ('Mayer-Sporer', 'Insertion of Infusion Dev into L Low Extrem, Open Approach');
insert into company (name, description) values ('Jaskolski Group', 'Hepatobiliary System and Pancreas, Occlusion');
insert into company (name, description) values ('Crona, Stokes and Boyer', 'Supplement L Ext Iliac Art with Synth Sub, Open Approach');
insert into company (name, description) values ('Ebert, Haley and Fay', 'Reposition Right Clavicle with Int Fix, Open Approach');
insert into company (name, description) values ('Hodkiewicz Inc', 'Dilate of Intracran Art with Drug-elut Intra, Open Approach');
insert into company (name, description) values ('Rempel, Wintheiser and Skiles', 'Transfer Right Foot Muscle with Subcu, Open Approach');
insert into company (name, description) values ('Hirthe Group', 'Removal of Synth Sub from Uterus & Cervix, Via Opening');
insert into company (name, description) values ('Cremin, Hintz and Stokes', 'Excision of Male Perineum, External Approach');
insert into company (name, description) values ('Prohaska-Powlowski', 'Release Ant Neck Subcu/Fascia, Extern Approach');
insert into company (name, description) values ('Heidenreich, Hermiston and Cremin', 'Supplement R Palatine Bone with Nonaut Sub, Open Approach');
insert into company (name, description) values ('Wyman and Sons', 'Replace R Int Mamm Art w Nonaut Sub, Perc Endo');
insert into company (name, description) values ('Brown-Bogan', 'Drainage of R Parietal Bone with Drain Dev, Perc Approach');
insert into company (name, description) values ('Bogan Group', 'Ventil, Resp/Circ Assess Circ Body w Mech Equip');
insert into company (name, description) values ('Funk-Bergnaum', 'Extirpation of Matter from Lower Lip, External Approach');
insert into company (name, description) values ('Christiansen, Spinka and Keebler', 'Other Procedures, Indwelling Device, Other Procedures');
insert into company (name, description) values ('Windler, Kuphal and Price', 'Repair Bilateral Seminal Vesicles, Perc Endo Approach');
insert into company (name, description) values ('Howell, Quigley and Gusikowski', 'Dilation of Pulmonary Trunk with Intralum Dev, Open Approach');
insert into company (name, description) values ('Zboncak-Stokes', 'Restriction of Right Ureter with Extralum Dev, Open Approach');
insert into company (name, description) values ('Bashirian-Witting', 'Supplement Hard Palate with Synth Sub, Perc Approach');
insert into company (name, description) values ('Purdy, Mraz and Feeney', 'Excision of Left Shoulder Tendon, Perc Endo Approach');
insert into company (name, description) values ('Goldner, Carter and Leannon', 'Drainage of Greater Omentum, Perc Endo Approach, Diagn');
insert into company (name, description) values ('Beer Group', 'Removal of Radioact Elem from Chest Wall, Extern Approach');
insert into company (name, description) values ('Heaney-Wolf', 'Insert of Intralum Dev into Hemiazygos Vein, Open Approach');
insert into company (name, description) values ('Corwin Group', 'Stereotactic Other Photon Radiosurgery of Prostate');
insert into company (name, description) values ('Bauch-Jerde', 'Bypass Left Femoral Artery to B Femor A, Open Approach');
insert into company (name, description) values ('Franecki-Stokes', 'Fusion Lumsac Jt w Autol Sub, Post Appr A Col, Perc Endo');
insert into company (name, description) values ('Hartmann, Von and Hagenes', 'Removal of Spacer from Left Carpal Joint, Perc Approach');
insert into company (name, description) values ('Hagenes Inc', 'Removal of Synth Sub from L Metacarpal, Perc Approach');
insert into company (name, description) values ('Runolfsdottir, Adams and Kutch', 'Excision of Left Sclera, External Approach');
insert into company (name, description) values ('Luettgen and Sons', 'Irrigation of Male Reprod using Irrigat, Via Opening, Diagn');
insert into company (name, description) values ('Jakubowski, Treutel and Ryan', 'Bypass Stomach to Transverse Colon, Endo');
insert into company (name, description) values ('Hartmann and Sons', 'Supplement R Brach Art with Nonaut Sub, Open Approach');
insert into company (name, description) values ('Ebert-Wisozk', 'Reposition Lumbar Spinal Cord, Percutaneous Approach');
insert into company (name, description) values ('Daniel, Barrows and McCullough', 'MRI of Fetal Spine using Oth Contrast, Unenh, Enhance');
insert into company (name, description) values ('Donnelly and Sons', 'Removal of Int Fix from R Wrist Jt, Perc Approach');
insert into company (name, description) values ('Pacocha, Friesen and Witting', 'Revision of Oth Dev in Male Perineum, Perc Endo Approach');
insert into company (name, description) values ('Cummings, Zemlak and Runte', 'Introduce Monoclonal Antibody in Mouth/Phar, Via Opening');
insert into company (name, description) values ('Cummings LLC', 'Removal of Bone Stim from Facial Bone, Perc Endo Approach');
insert into company (name, description) values ('Wehner Group', 'Replacement of Left Radius with Synth Sub, Perc Approach');
insert into company (name, description) values ('Wiegand, Flatley and Breitenberg', 'Fragmentation in Left Fallopian Tube, Open Approach');
insert into company (name, description) values ('Morar-Parisian', 'Repair Left Lower Extremity, Open Approach');
insert into company (name, description) values ('O''Reilly, Schultz and Effertz', 'Inspection of Right Ankle Region, Percutaneous Approach');
insert into company (name, description) values ('Kemmer, Feil and Hessel', 'Plain Radiography of Bi Pelvic Vein using L Osm Contrast');
insert into company (name, description) values ('Glover-Kilback', 'Drainage of Nose, Percutaneous Endoscopic Approach, Diagn');
insert into company (name, description) values ('Kshlerin, Lockman and Nikolaus', 'Extirpation of Matter from Splenic Artery, Perc Approach');
insert into company (name, description) values ('Gleason-Hermiston', 'Reposition Trigeminal Nerve, Open Approach');
insert into company (name, description) values ('Zboncak Inc', 'Supplement Perineum Muscle with Nonaut Sub, Open Approach');
insert into company (name, description) values ('Barton, Yost and Heaney', 'Replacement of Left Clavicle with Autol Sub, Perc Approach');
insert into company (name, description) values ('Stehr, Emard and D''Amore', 'Replace L Hand Skin w Nonaut Sub, Full Thick, Extern');
insert into company (name, description) values ('Casper, Weissnat and Rosenbaum', 'Restriction of Right Main Bronchus, Open Approach');
insert into company (name, description) values ('O''Conner-Collier', 'Transfer Peroneal Nerve to Femoral Nerve, Open Approach');
insert into company (name, description) values ('Mohr, Kilback and Kunze', 'ROM & Jt Mobility Trmt Musculosk Whole w Orthosis');
insert into company (name, description) values ('Moen-Monahan', 'Restriction of Pancreatic Duct with Intralum Dev, Endo');
insert into company (name, description) values ('Cummerata and Sons', 'Beam Radiation of Soft Palate using Photons 1 - 10 MeV');
insert into company (name, description) values ('Koelpin-Becker', 'Drainage of Left Vocal Cord, Via Opening');
insert into company (name, description) values ('Ryan Inc', 'LDR Brachytherapy of Bladder using Iridium 192');
insert into company (name, description) values ('Johnson Inc', 'Excision of Appendix, Open Approach');
insert into company (name, description) values ('Mayert-Glover', 'Removal of Ext Fix from R Metacarpophal Jt, Extern Approach');
insert into company (name, description) values ('Quitzon, Kling and Wyman', 'Replace of L Pulm Vein with Synth Sub, Perc Endo Approach');
insert into company (name, description) values ('Olson-Jacobson', 'Revision of Int Fix in R Tarsal Jt, Extern Approach');
insert into company (name, description) values ('Kovacek, Padberg and Abbott', 'Removal of Ext Fix from L Finger Phalanx, Perc Endo Approach');
insert into company (name, description) values ('Ruecker and Sons', 'Replacement of Esophageal Vein with Autol Sub, Open Approach');
insert into company (name, description) values ('Olson-King', 'Dilation of L Int Mamm Art with 2 Drug-elut, Open Approach');
insert into company (name, description) values ('Zulauf-Bruen', 'Extirpation of Matter from Duodenum, Endo');
insert into company (name, description) values ('Greenholt, Homenick and Hartmann', 'Repair Left Ulnar Artery, Open Approach');
insert into company (name, description) values ('Keeling, Tromp and Hagenes', 'Supplement Perineum Muscle with Autol Sub, Open Approach');
insert into company (name, description) values ('Green, Anderson and VonRueden', 'Reposition Right Mandible, Open Approach');
insert into company (name, description) values ('Hand-Hintz', 'Excision of Appendix, Open Approach');
insert into company (name, description) values ('Runolfsdottir-Weissnat', 'Dilation of Right Main Bronchus, Perc Endo Approach');
insert into company (name, description) values ('Zieme and Sons', 'Supplement L Hepatic Duct with Synth Sub, Perc Endo Approach');
insert into company (name, description) values ('Aufderhar-Considine', 'Removal of Extralum Dev from Up Art, Perc Endo Approach');
insert into company (name, description) values ('Blanda-Olson', 'Transfer Optic Nerve to Abducens Nerve, Open Approach');
insert into company (name, description) values ('Thiel Inc', 'Measurement of Cardiac Output, Percutaneous Approach');
insert into company (name, description) values ('Zemlak-Roob', 'Extirpation of Matter from Right Ulnar Artery, Perc Approach');
insert into company (name, description) values ('Veum-Emard', 'Bypass Transverse Colon to Rectum, Open Approach');
insert into company (name, description) values ('Deckow, Yost and Hackett', 'Replacement of R Post Tib Art with Nonaut Sub, Open Approach');
insert into company (name, description) values ('Tremblay LLC', 'Release Right Trunk Tendon, Percutaneous Approach');
insert into company (name, description) values ('Kutch-Schaefer', 'Replace R Ext Iliac Art w Nonaut Sub, Perc Endo');
insert into company (name, description) values ('Daniel, Flatley and Wehner', 'Extirpation of Matter from Respiratory Tract, Open Approach');
insert into company (name, description) values ('Mann and Sons', 'Dilate R Ext Carotid, Bifurc, w Intralum Dev, Open');
insert into company (name, description) values ('Bergstrom-Gislason', 'Drainage of Innominate Artery, Open Approach');
insert into company (name, description) values ('Bayer, Haley and Walker', 'Drainage of Left Hip Joint, Perc Endo Approach, Diagn');
insert into company (name, description) values ('Leffler LLC', 'Extirpate of Matter from L Axilla Art, Bifurc, Open Approach');
insert into company (name, description) values ('Keeling, Mann and Yost', 'Destruction of Left Sphenoid Sinus, Open Approach');
insert into company (name, description) values ('Crist-Lockman', 'Repair Glossopharyngeal Nerve, Perc Endo Approach');
insert into company (name, description) values ('Carter Group', 'Extraction of Right Vocal Cord, Percutaneous Approach');
insert into company (name, description) values ('Miller-Keebler', 'Supplement Left Lacrimal Duct with Synth Sub, Via Opening');
insert into company (name, description) values ('Bergnaum-Boyle', 'Excision of Superior Mesenteric Artery, Perc Approach');
insert into company (name, description) values ('Bode LLC', 'Dilation of L Hand Art with 4+ Intralum Dev, Open Approach');
insert into company (name, description) values ('Conn-Vandervort', 'Resection of Right Axillary Lymphatic, Open Approach');
insert into company (name, description) values ('Hessel, Murray and Bode', 'Change Nasal Packing Material');
insert into company (name, description) values ('Goyette, Paucek and Kulas', 'Excision of Left Lower Lung Lobe, Open Approach');
insert into company (name, description) values ('Davis, O''Kon and Schamberger', 'Comm/Cognit Skill Treatment of Neuro Body using Oth Equip');
insert into company (name, description) values ('Hintz, McKenzie and Stanton', 'Extirpation of Matter from Right Iris, External Approach');
insert into company (name, description) values ('Blick and Sons', 'Extirpate matter from R Less Saphenous, Perc Endo');
insert into company (name, description) values ('Hoppe, Murphy and Hagenes', 'Insertion of Radioact Elem into L Buttock, Perc Approach');
insert into company (name, description) values ('Bednar-Hyatt', 'Release Right Basilic Vein, Percutaneous Approach');
insert into company (name, description) values ('Mitchell-Pfeffer', 'Inspection of Ureter, Open Approach');
insert into company (name, description) values ('Purdy-Fay', 'Supplement C-thor Jt with Autol Sub, Perc Approach');
insert into company (name, description) values ('Leffler Inc', 'Restriction of Ascending Colon, Percutaneous Approach');
insert into company (name, description) values ('Larkin-Monahan', 'Occlusion of L Neck Lymph with Extralum Dev, Perc Approach');
insert into company (name, description) values ('Hamill, Wiegand and Schuppe', 'Alteration of L Ext Ear with Autol Sub, Open Approach');
insert into company (name, description) values ('Huel-Breitenberg', 'Insertion of Infusion Device into L Elbow, Perc Approach');
insert into company (name, description) values ('Bergstrom, Von and Marks', 'Revision of Spacer in R Metatarsophal Jt, Extern Approach');
insert into company (name, description) values ('Zieme, Wehner and Hettinger', 'Fusion of L Metatarsophal Jt with Synth Sub, Open Approach');
insert into company (name, description) values ('Moore-Franecki', 'Supplement L Low Leg Muscle w Autol Sub, Perc Endo');
insert into company (name, description) values ('Balistreri LLC', 'abce');
insert into company (name, description) values ('Balistreri LLC', 'abcf');
insert into company (name, description) values ('Balistreri LLC', 'abcg');
insert into company (name, description) values ('Balistreri LLC', 'abci');
insert into company (name, description) values ('Balistreri LLC', 'abch');
insert into company (name, description) values ('Balistreri LLC', 'abcj');
insert into company (name, description) values ('Balistreri LLC', 'abck');
insert into company (name, description) values ('Balistreri LLC', 'abcl');
